/*
 * DNet eBusiness Suite
 * Copyright: 2008-2012 Nan21 Electronics SRL. All rights reserved.
 * Use is subject to license terms. 
 */   	 
Ext.define("net.nan21.dnet.module.sd.order.ds.model.SalesOrderDs" ,{
	extend: 'Ext.data.Model',
	fields: [ 
		{name:"id", type:"int", useNull:true},
		{name:"uuid", type:"string"},
		{name:"clientId", type:"int", useNull:true},
		{name:"createdAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdBy", type:"string"},
		{name:"modifiedBy", type:"string"},
		{name:"version", type:"int", useNull:true},
		{name:"entityFQN", type:"string"},
		{name:"code", type:"string"},
		{name:"docDate", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"supplierId", type:"int", useNull:true},
		{name:"supplier", type:"string"},
		{name:"docTypeId", type:"int", useNull:true},
		{name:"docType", type:"string"},
		{name:"customerId", type:"int", useNull:true},
		{name:"customerUuid", type:"string"},
		{name:"customerCode", type:"string"},
		{name:"customer", type:"string"},
		{name:"currencyId", type:"int", useNull:true},
		{name:"currency", type:"string"},
		{name:"priceListId", type:"int", useNull:true},
		{name:"priceList", type:"string"},
		{name:"paymentMethodId", type:"int", useNull:true},
		{name:"paymentMethod", type:"string"},
		{name:"paymentTermId", type:"int", useNull:true},
		{name:"paymentTerm", type:"string"},
		{name:"deliveryMethodId", type:"int", useNull:true},
		{name:"deliveryMethod", type:"string"},
		{name:"plannedDeliveryDate", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"deliveryNotes", type:"string"},
		{name:"inventoryId", type:"int", useNull:true},
		{name:"inventory", type:"string"},
		{name:"billToId", type:"int", useNull:true},
		{name:"billToUuid", type:"string"},
		{name:"billToCode", type:"string"},
		{name:"billTo", type:"string"},
		{name:"billToLocationId", type:"int", useNull:true},
		{name:"billToLocation", type:"string"},
		{name:"billToContactId", type:"int", useNull:true},
		{name:"billToContact", type:"string"},
		{name:"shipToId", type:"int", useNull:true},
		{name:"shipToUuid", type:"string"},
		{name:"shipToCode", type:"string"},
		{name:"shipTo", type:"string"},
		{name:"shipToLocationId", type:"int", useNull:true},
		{name:"shipToLocation", type:"string"},
		{name:"shipToContactId", type:"int", useNull:true},
		{name:"shipToContact", type:"string"},
		{name:"carrierId", type:"int", useNull:true},
		{name:"carrier", type:"string"},
		{name:"totalAmount", type:"float", useNull:true},
		{name:"totalNetAmount", type:"float", useNull:true},
		{name:"totalTaxAmount", type:"float", useNull:true},
		{name:"confirmed", type:"boolean"},
		{name:"invoiced", type:"boolean"},
		{name:"delivered", type:"boolean"},
		{name:"className", type:"string"},
		{name:"businessObject", type:"string"}
	]
});

Ext.define("net.nan21.dnet.module.sd.order.ds.model.SalesOrderDsFilter" ,{
	extend: 'Ext.data.Model',
	fields: [ 
		{name:"id", type:"int", useNull:true},
		{name:"uuid", type:"string"},
		{name:"createdAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdAt_From",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdAt_To",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedAt", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedAt_From",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"modifiedAt_To",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"createdBy", type:"string"},
		{name:"modifiedBy", type:"string"},
		{name:"entityFQN", type:"string"},
		{name:"code", type:"string"},
		{name:"docDate", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"docDate_From",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"docDate_To",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"supplierId", type:"int", useNull:true},
		{name:"supplierId_From",type:"int", useNull:true},
		{name:"supplierId_To",type:"int", useNull:true},
		{name:"supplier", type:"string"},
		{name:"docTypeId", type:"int", useNull:true},
		{name:"docTypeId_From",type:"int", useNull:true},
		{name:"docTypeId_To",type:"int", useNull:true},
		{name:"docType", type:"string"},
		{name:"customerId", type:"int", useNull:true},
		{name:"customerId_From",type:"int", useNull:true},
		{name:"customerId_To",type:"int", useNull:true},
		{name:"customerUuid", type:"string"},
		{name:"customerCode", type:"string"},
		{name:"customer", type:"string"},
		{name:"currencyId", type:"int", useNull:true},
		{name:"currencyId_From",type:"int", useNull:true},
		{name:"currencyId_To",type:"int", useNull:true},
		{name:"currency", type:"string"},
		{name:"priceListId", type:"int", useNull:true},
		{name:"priceListId_From",type:"int", useNull:true},
		{name:"priceListId_To",type:"int", useNull:true},
		{name:"priceList", type:"string"},
		{name:"paymentMethodId", type:"int", useNull:true},
		{name:"paymentMethodId_From",type:"int", useNull:true},
		{name:"paymentMethodId_To",type:"int", useNull:true},
		{name:"paymentMethod", type:"string"},
		{name:"paymentTermId", type:"int", useNull:true},
		{name:"paymentTermId_From",type:"int", useNull:true},
		{name:"paymentTermId_To",type:"int", useNull:true},
		{name:"paymentTerm", type:"string"},
		{name:"deliveryMethodId", type:"int", useNull:true},
		{name:"deliveryMethodId_From",type:"int", useNull:true},
		{name:"deliveryMethodId_To",type:"int", useNull:true},
		{name:"deliveryMethod", type:"string"},
		{name:"plannedDeliveryDate", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"plannedDeliveryDate_From",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"plannedDeliveryDate_To",type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"deliveryNotes", type:"string"},
		{name:"inventoryId", type:"int", useNull:true},
		{name:"inventoryId_From",type:"int", useNull:true},
		{name:"inventoryId_To",type:"int", useNull:true},
		{name:"inventory", type:"string"},
		{name:"billToId", type:"int", useNull:true},
		{name:"billToId_From",type:"int", useNull:true},
		{name:"billToId_To",type:"int", useNull:true},
		{name:"billToUuid", type:"string"},
		{name:"billToCode", type:"string"},
		{name:"billTo", type:"string"},
		{name:"billToLocationId", type:"int", useNull:true},
		{name:"billToLocationId_From",type:"int", useNull:true},
		{name:"billToLocationId_To",type:"int", useNull:true},
		{name:"billToLocation", type:"string"},
		{name:"billToContactId", type:"int", useNull:true},
		{name:"billToContactId_From",type:"int", useNull:true},
		{name:"billToContactId_To",type:"int", useNull:true},
		{name:"billToContact", type:"string"},
		{name:"shipToId", type:"int", useNull:true},
		{name:"shipToId_From",type:"int", useNull:true},
		{name:"shipToId_To",type:"int", useNull:true},
		{name:"shipToUuid", type:"string"},
		{name:"shipToCode", type:"string"},
		{name:"shipTo", type:"string"},
		{name:"shipToLocationId", type:"int", useNull:true},
		{name:"shipToLocationId_From",type:"int", useNull:true},
		{name:"shipToLocationId_To",type:"int", useNull:true},
		{name:"shipToLocation", type:"string"},
		{name:"shipToContactId", type:"int", useNull:true},
		{name:"shipToContactId_From",type:"int", useNull:true},
		{name:"shipToContactId_To",type:"int", useNull:true},
		{name:"shipToContact", type:"string"},
		{name:"carrierId", type:"int", useNull:true},
		{name:"carrierId_From",type:"int", useNull:true},
		{name:"carrierId_To",type:"int", useNull:true},
		{name:"carrier", type:"string"},
		{name:"totalAmount", type:"float", useNull:true},
		{name:"totalAmount_From",type:"float", useNull:true},
		{name:"totalAmount_To",type:"float", useNull:true},
		{name:"totalNetAmount", type:"float", useNull:true},
		{name:"totalNetAmount_From",type:"float", useNull:true},
		{name:"totalNetAmount_To",type:"float", useNull:true},
		{name:"totalTaxAmount", type:"float", useNull:true},
		{name:"totalTaxAmount_From",type:"float", useNull:true},
		{name:"totalTaxAmount_To",type:"float", useNull:true},
		{name:"confirmed", type:"boolean", useNull:true},
		{name:"invoiced", type:"boolean", useNull:true},
		{name:"delivered", type:"boolean", useNull:true},
		{name:"className", type:"string"},
		{name:"businessObject", type:"string"}
	] 
});
	
Ext.define("net.nan21.dnet.module.sd.order.ds.param.SalesOrderDsParam", {
	extend: 'Ext.data.Model',
	fields: [ 
		{name:"delivDocTypeId", type:"int", useNull:true},
		{name:"delivDocType", type:"string"},
		{name:"delivTxTypeId", type:"int", useNull:true},
		{name:"delivTxType", type:"string"},
		{name:"delivEventData", type:"date", dateFormat:Dnet.MODEL_DATE_FORMAT},
		{name:"invDocTypeId", type:"int", useNull:true},
		{name:"invDocType", type:"string"}
	]
}); 
 